import { useEffect, useMemo, useState } from 'react';
import {
  Activity, AlertTriangle, Boxes, ClipboardCheck, Factory, Gauge, Hammer, LayoutDashboard,
  LogOut, Menu, PackagePlus, Settings2, ShoppingCart, ShieldCheck, Users, X, Plus, Search,
  RefreshCw, CheckCircle2, Clock3, Wrench, ChevronRight
} from 'lucide-react';
import { api } from './api';

type User = { id:number; name:string; email:string; role:string };
type Dashboard = { materials:number; prod:any[]; qc:any[]; maint:any[]; totalStock:number; lowStock:any[] };

const fmt = new Intl.NumberFormat('id-ID');
const money = new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0});

const nav = [
  {key:'dashboard', label:'Dashboard', icon:LayoutDashboard},
  {key:'production', label:'Produksi', icon:Factory},
  {key:'inventory', label:'Inventory', icon:Boxes},
  {key:'purchasing', label:'Purchasing', icon:ShoppingCart},
  {key:'quality', label:'Quality Control', icon:ClipboardCheck},
  {key:'maintenance', label:'Maintenance', icon:Hammer},
  {key:'audit', label:'Audit Log', icon:ShieldCheck, roles:['ADMIN','MANAGER']},
  {key:'users', label:'User & Role', icon:Users, roles:['ADMIN']},
];

function Pill({children,tone='neutral'}:{children:any,tone?:string}) { return <span className={`pill ${tone}`}>{children}</span> }
function StatCard({label,value,icon:Icon,sub}:{label:string;value:any;icon:any;sub?:string}) { return <div className="stat"><div className="stat-icon"><Icon size={18}/></div><div><div className="stat-label">{label}</div><div className="stat-value">{value}</div>{sub&&<div className="stat-sub">{sub}</div>}</div></div> }

function Login({onLogin}:{onLogin:(u:User)=>void}) {
  const [email,setEmail]=useState('admin@srikandi.local');
  const [password,setPassword]=useState('Demo123!');
  const [loading,setLoading]=useState(false); const [error,setError]=useState('');
  async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setError('');try{const r=await api<{user:User}>('/api/auth/login',{method:'POST',body:JSON.stringify({email,password})});onLogin(r.user)}catch(err:any){setError(err.message)}finally{setLoading(false)}}
  return <div className="login-shell"><div className="login-card"><div className="brand-mark"><Factory size={26}/></div><h1>Srikandi Factory OS</h1><p className="muted">Operational control center untuk pabrik</p><form onSubmit={submit} className="stack"><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} /></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} /></label>{error&&<div className="alert danger">{error}</div>}<button className="btn primary" disabled={loading}>{loading?'Masuk...':'Masuk ke sistem'}</button></form><div className="demo-box"><b>Demo testing</b><br/>admin@srikandi.local · Demo123!</div></div></div>
}

function Shell({user,onLogout,children,active,onNav}:{user:User;onLogout:()=>void;children:any;active:string;onNav:(k:string)=>void}) {
  const [open,setOpen]=useState(false);
  const items=nav.filter(n=>!n.roles||n.roles.includes(user.role));
  return <div className="app-shell"><aside className={open?'sidebar open':'sidebar'}><div className="sidebar-top"><div className="brand"><div className="brand-mark small"><Factory size={18}/></div><div><b>SRIKANDI</b><span>FACTORY OS</span></div></div><button className="icon-btn mobile" onClick={()=>setOpen(false)}><X/></button></div><div className="nav-section">OPERATIONS</div><nav>{items.map(item=>{const Icon=item.icon;return <button key={item.key} className={active===item.key?'nav-btn active':'nav-btn'} onClick={()=>{onNav(item.key);setOpen(false)}}><Icon size={18}/><span>{item.label}</span></button>})}</nav><div className="sidebar-bottom"><div className="user-mini"><div className="avatar">{user.name.charAt(0)}</div><div><b>{user.name}</b><span>{user.role}</span></div></div><button className="nav-btn" onClick={onLogout}><LogOut size={18}/><span>Keluar</span></button></div></aside><main className="main"><header className="topbar"><button className="icon-btn mobile" onClick={()=>setOpen(true)}><Menu/></button><div><div className="eyebrow">PT SRIKANDI · INTERNAL OPERATIONS</div><div className="top-title">Control Center</div></div><div className="top-actions"><div className="env-chip"><span className="dot"/>TESTING</div></div></header><section className="content">{children}</section></main></div>
}

function DashboardPage(){
 const [data,setData]=useState<Dashboard|null>(null); const [loading,setLoading]=useState(true);
 const load=()=>{setLoading(true);api<Dashboard>('/api/dashboard').then(setData).finally(()=>setLoading(false))}; useEffect(load,[]);
 if(loading||!data) return <div className="loading"><RefreshCw className="spin"/> Memuat dashboard...</div>;
 const map=(arr:any[])=>Object.fromEntries(arr.map(x=>[x.status||x.result,x.value])); const p=map(data.prod),q=map(data.qc),m=map(data.maint);
 return <div className="page"><div className="page-head"><div><h2>Dashboard Operasional</h2><p>Pantau produksi, material, QC, dan maintenance dari satu tempat.</p></div><button className="btn ghost" onClick={load}><RefreshCw size={16}/>Refresh</button></div><div className="stats-grid"><StatCard label="Material Aktif" value={fmt.format(data.materials)} icon={Boxes} sub="master inventory"/><StatCard label="Stok Total" value={fmt.format(data.totalStock)} icon={PackagePlus} sub="unit akumulatif"/><StatCard label="Produksi Berjalan" value={p.RUNNING||0} icon={Activity} sub={`${p.PLANNED||0} planned`} /><StatCard label="QC Rework" value={q.REWORK||0} icon={AlertTriangle} sub={`${q.FAIL||0} failed`} /></div><div className="grid-2"><section className="panel"><div className="panel-head"><div><h3>Health Produksi</h3><span className="muted">Distribusi status production order</span></div><Gauge size={18}/></div><div className="bar-list">{[['PLANNED','Planned'],['RUNNING','Running'],['QC','QC'],['DONE','Done'],['CANCELLED','Cancelled']].map(([k,l])=><div className="bar-row" key={k}><span>{l}</span><div className="bar-track"><div className="bar-fill" style={{width:`${Math.min(100,(p[k]||0)*15)}%`}}/></div><b>{p[k]||0}</b></div>)}</div></section><section className="panel"><div className="panel-head"><div><h3>Alert Stok</h3><span className="muted">Material di bawah minimum stock</span></div><AlertTriangle size={18}/></div>{data.lowStock.length===0?<div className="empty">Semua stok berada di atas minimum.</div>:<div className="compact-table">{data.lowStock.map((x:any)=><div className="compact-row" key={x.id}><div><b>{x.sku}</b><span>{x.name}</span></div><div className="danger-text">{fmt.format(x.current_stock)} / {fmt.format(x.min_stock)} {x.unit}</div></div>)}</div>}</section></div><div className="grid-3"><section className="panel metric-panel"><Clock3/><div><span>QC Pending</span><b>{q.PENDING||0}</b></div></section><section className="panel metric-panel"><Wrench/><div><span>Maintenance Open</span><b>{m.OPEN||0}</b></div></section><section className="panel metric-panel"><CheckCircle2/><div><span>QC Pass</span><b>{q.PASS||0}</b></div></section></div></div>
}

function ProductionPage(){
 const [items,setItems]=useState<any[]>([]); const [q,setQ]=useState(''); const [show,setShow]=useState(false);
 const load=()=>api<{items:any[]}>('/api/production-orders?q='+encodeURIComponent(q)).then(r=>setItems(r.items)); useEffect(load,[q]);
 async function status(id:number,status:string){await api(`/api/production-orders/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});load()}
 return <div className="page"><PageHead title="Produksi" desc="Production order, status line, prioritas, dan monitoring batch." action={<button className="btn primary" onClick={()=>setShow(true)}><Plus size={16}/>Production Order</button>}/><div className="toolbar"><div className="search"><Search size={16}/><input placeholder="Cari kode, produk, mesin..." value={q} onChange={e=>setQ(e.target.value)}/></div><div className="toolbar-note">{items.length} order</div></div><section className="panel table-panel"><table><thead><tr><th>Order</th><th>Produk</th><th>Qty</th><th>Prioritas</th><th>Status</th><th>Mesin</th><th>Aksi</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><b>{x.code}</b><div className="subcell">{x.created_at?.slice(0,10)}</div></td><td>{x.product_name}</td><td>{fmt.format(x.quantity)} {x.unit}</td><td><Pill tone={x.priority==='URGENT'?'danger':x.priority==='HIGH'?'warn':'neutral'}>{x.priority}</Pill></td><td><Pill tone={x.status==='DONE'?'success':x.status==='QC'?'purple':x.status==='RUNNING'?'blue':x.status==='CANCELLED'?'danger':'neutral'}>{x.status}</Pill></td><td>{x.machine||'—'}</td><td><select className="mini-select" value={x.status} onChange={e=>status(x.id,e.target.value)}><option>PLANNED</option><option>RUNNING</option><option>QC</option><option>DONE</option><option>CANCELLED</option></select></td></tr>)}</tbody></table></section>{show&&<Modal title="Buat Production Order" onClose={()=>setShow(false)}><ProductionForm onDone={()=>{setShow(false);load()}}/></Modal>}</div>
}
function ProductionForm({onDone}:{onDone:()=>void}){const [f,setF]=useState<any>({code:'PO-',product_name:'',quantity:1000,unit:'PCS',priority:'MEDIUM',machine:'',planned_start:'',planned_end:'',notes:''});const [err,setErr]=useState('');async function save(e:React.FormEvent){e.preventDefault();setErr('');try{await api('/api/production-orders',{method:'POST',body:JSON.stringify({...f,quantity:Number(f.quantity)})});onDone()}catch(e:any){setErr(e.message)}}return <form className="form-grid" onSubmit={save}>{err&&<div className="alert danger full">{err}</div>}<Field label="Kode" value={f.code} onChange={(v:any)=>setF({...f,code:v})}/><Field label="Produk" value={f.product_name} onChange={(v:any)=>setF({...f,product_name:v})}/><Field label="Quantity" type="number" value={f.quantity} onChange={(v:any)=>setF({...f,quantity:v})}/><Field label="Unit" value={f.unit} onChange={(v:any)=>setF({...f,unit:v})}/><Field label="Prioritas" type="select" options={['LOW','MEDIUM','HIGH','URGENT']} value={f.priority} onChange={(v:any)=>setF({...f,priority:v})}/><Field label="Mesin" value={f.machine} onChange={(v:any)=>setF({...f,machine:v})}/><Field label="Planned Start" type="date" value={f.planned_start} onChange={(v:any)=>setF({...f,planned_start:v})}/><Field label="Planned End" type="date" value={f.planned_end} onChange={(v:any)=>setF({...f,planned_end:v})}/><div className="field full"><label>Notes<textarea value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></label></div><div className="modal-actions full"><button type="button" className="btn ghost" onClick={onDone}>Batal</button><button className="btn primary">Simpan</button></div></form>}

function InventoryPage(){const [items,setItems]=useState<any[]>([]);const [moves,setMoves]=useState<any[]>([]);const [show,setShow]=useState(false);const [showMove,setShowMove]=useState(false);const load=async()=>{const [m,sm]=await Promise.all([api<{items:any[]}>('/api/materials'),api<{items:any[]}>('/api/stock-movements')]);setItems(m.items);setMoves(sm.items)};useEffect(()=>{load()},[]);return <div className="page"><PageHead title="Inventory" desc="Master material, stock level, lokasi penyimpanan, dan stock ledger." action={<div className="head-actions"><button className="btn ghost" onClick={()=>setShowMove(true)}><PackagePlus size={16}/>Mutasi Stok</button><button className="btn primary" onClick={()=>setShow(true)}><Plus size={16}/>Material</button></div>}/><section className="panel table-panel"><table><thead><tr><th>SKU</th><th>Material</th><th>Kategori</th><th>Stok</th><th>Minimum</th><th>Lokasi</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><b>{x.sku}</b></td><td>{x.name}</td><td><Pill>{x.category}</Pill></td><td className={x.current_stock<x.min_stock?'danger-text':''}><b>{fmt.format(x.current_stock)}</b> {x.unit}</td><td>{fmt.format(x.min_stock)} {x.unit}</td><td>{x.location}</td></tr>)}</tbody></table></section><section className="panel table-panel ledger-panel"><div className="panel-head"><div><h3>Stock Ledger</h3><span className="muted">100 mutasi terbaru</span></div><PackagePlus size={18}/></div><table><thead><tr><th>Waktu</th><th>Material</th><th>Tipe</th><th>Qty</th><th>User</th><th>Catatan</th></tr></thead><tbody>{moves.map(x=><tr key={x.id}><td>{x.created_at?.slice(0,16).replace('T',' ')}</td><td><b>{x.sku}</b><div className="subcell">{x.material_name}</div></td><td><Pill tone={x.movement_type==='IN'?'success':x.movement_type==='OUT'?'warn':'blue'}>{x.movement_type}</Pill></td><td>{fmt.format(x.quantity)}</td><td>{x.user_name||'—'}</td><td>{x.notes||'—'}</td></tr>)}</tbody></table></section>{show&&<Modal title="Tambah Material" onClose={()=>setShow(false)}><MaterialForm onDone={()=>{setShow(false);load()}}/></Modal>}{showMove&&<Modal title="Mutasi Stok" onClose={()=>setShowMove(false)}><StockMoveForm materials={items} onDone={()=>{setShowMove(false);load()}}/></Modal>}</div>}
function StockMoveForm({materials,onDone}:{materials:any[];onDone:()=>void}){const[f,setF]=useState<any>({material_id:materials[0]?.id||'',movement_type:'IN',quantity:1,notes:''});const[err,setErr]=useState('');async function save(e:React.FormEvent){e.preventDefault();try{await api('/api/stock-movements',{method:'POST',body:JSON.stringify({...f,material_id:Number(f.material_id),quantity:Number(f.quantity)})});onDone()}catch(e:any){setErr(e.message)}}return <form className="form-grid" onSubmit={save}>{err&&<div className="alert danger full">{err}</div>}<Field label="Material" type="select" options={materials.map(x=>String(x.id))} value={String(f.material_id)} onChange={(v:any)=>setF({...f,material_id:Number(v)})}/><Field label="Tipe Mutasi" type="select" options={['IN','OUT','ADJUSTMENT']} value={f.movement_type} onChange={(v:any)=>setF({...f,movement_type:v})}/><Field label="Quantity" type="number" value={f.quantity} onChange={(v:any)=>setF({...f,quantity:v})}/><div className="field full"><label>Catatan<textarea value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></label></div><div className="modal-actions full"><button type="button" className="btn ghost" onClick={onDone}>Batal</button><button className="btn primary">Simpan Mutasi</button></div></form>}

function MaterialForm({onDone}:{onDone:()=>void}){const [f,setF]=useState<any>({sku:'MAT-',name:'',category:'RAW MATERIAL',unit:'KG',min_stock:0,current_stock:0,location:'MAIN'});const [err,setErr]=useState('');async function save(e:React.FormEvent){e.preventDefault();try{await api('/api/materials',{method:'POST',body:JSON.stringify({...f,min_stock:Number(f.min_stock),current_stock:Number(f.current_stock)})});onDone()}catch(e:any){setErr(e.message)}}return <form className="form-grid" onSubmit={save}>{err&&<div className="alert danger full">{err}</div>}<Field label="SKU" value={f.sku} onChange={(v:any)=>setF({...f,sku:v})}/><Field label="Nama Material" value={f.name} onChange={(v:any)=>setF({...f,name:v})}/><Field label="Kategori" type="select" options={['RAW MATERIAL','PACKAGING','MAINTENANCE','FINISHED GOOD']} value={f.category} onChange={(v:any)=>setF({...f,category:v})}/><Field label="Unit" value={f.unit} onChange={(v:any)=>setF({...f,unit:v})}/><Field label="Minimum Stock" type="number" value={f.min_stock} onChange={(v:any)=>setF({...f,min_stock:v})}/><Field label="Stock Awal" type="number" value={f.current_stock} onChange={(v:any)=>setF({...f,current_stock:v})}/><Field label="Lokasi" value={f.location} onChange={(v:any)=>setF({...f,location:v})}/><div className="modal-actions full"><button type="button" className="btn ghost" onClick={onDone}>Batal</button><button className="btn primary">Simpan</button></div></form>}

function PurchasingPage(){const [items,setItems]=useState<any[]>([]);useEffect(()=>{api<{items:any[]}>('/api/purchase-orders').then(r=>setItems(r.items))},[]);return <div className="page"><PageHead title="Purchasing" desc="Purchase order dan penerimaan material dari supplier." action={<button className="btn ghost" disabled><Plus size={16}/>PO (demo berikutnya)</button>}/><section className="panel table-panel"><table><thead><tr><th>PO</th><th>Supplier</th><th>Status</th><th>Expected</th><th>Total</th></tr></thead><tbody>{items.length?items.map(x=><tr key={x.id}><td><b>{x.code}</b></td><td>{x.supplier_name}</td><td><Pill tone={x.status==='RECEIVED'?'success':x.status==='APPROVED'?'blue':'neutral'}>{x.status}</Pill></td><td>{x.expected_date||'—'}</td><td>{money.format(x.total_amount||0)}</td></tr>):<tr><td colSpan={5}><div className="empty">Belum ada purchase order.</div></td></tr>}</tbody></table></section></div>}

function QualityPage(){const [items,setItems]=useState<any[]>([]);const [orders,setOrders]=useState<any[]>([]);const[show,setShow]=useState(false);const load=async()=>{const[q,p]=await Promise.all([api<{items:any[]}>('/api/qc-inspections'),api<{items:any[]}>('/api/production-orders')]);setItems(q.items);setOrders(p.items)};useEffect(()=>{load()},[]);return <div className="page"><PageHead title="Quality Control" desc="Catat hasil inspeksi, defect, dan keputusan batch." action={<button className="btn primary" onClick={()=>setShow(true)}><Plus size={16}/>Inspeksi QC</button>}/><section className="panel table-panel"><table><thead><tr><th>QC</th><th>Production Order</th><th>Inspector</th><th>Result</th><th>Sample</th><th>Defect</th><th>Inspected</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><b>{x.code}</b></td><td>{x.production_code||'—'}<div className="subcell">{x.product_name||''}</div></td><td>{x.inspector_name||'—'}</td><td><Pill tone={x.result==='PASS'?'success':x.result==='REWORK'?'warn':x.result==='FAIL'?'danger':'neutral'}>{x.result}</Pill></td><td>{x.sample_size}</td><td className={x.defect_count>5?'danger-text':''}>{x.defect_count}</td><td>{x.inspected_at?.slice(0,16).replace('T',' ')||'—'}</td></tr>)}</tbody></table></section>{show&&<Modal title="Catat Inspeksi QC" onClose={()=>setShow(false)}><QCForm orders={orders} onDone={()=>{setShow(false);load()}}/></Modal>}</div>}
function QCForm({orders,onDone}:{orders:any[];onDone:()=>void}){const[f,setF]=useState<any>({code:'QC-',production_order_id:orders[0]?.id||'',result:'PASS',sample_size:100,defect_count:0,remarks:''});const[err,setErr]=useState('');async function save(e:React.FormEvent){e.preventDefault();try{await api('/api/qc-inspections',{method:'POST',body:JSON.stringify({...f,production_order_id:Number(f.production_order_id),sample_size:Number(f.sample_size),defect_count:Number(f.defect_count)})});onDone()}catch(e:any){setErr(e.message)}}return <form className="form-grid" onSubmit={save}>{err&&<div className="alert danger full">{err}</div>}<Field label="Kode QC" value={f.code} onChange={(v:any)=>setF({...f,code:v})}/><Field label="Production Order" type="select" options={orders.map(x=>String(x.id))} value={String(f.production_order_id)} onChange={(v:any)=>setF({...f,production_order_id:Number(v)})}/><Field label="Result" type="select" options={['PASS','FAIL','REWORK','PENDING']} value={f.result} onChange={(v:any)=>setF({...f,result:v})}/><Field label="Sample Size" type="number" value={f.sample_size} onChange={(v:any)=>setF({...f,sample_size:v})}/><Field label="Defect Count" type="number" value={f.defect_count} onChange={(v:any)=>setF({...f,defect_count:v})}/><div className="field full"><label>Remarks<textarea value={f.remarks} onChange={e=>setF({...f,remarks:e.target.value})}/></label></div><div className="modal-actions full"><button type="button" className="btn ghost" onClick={onDone}>Batal</button><button className="btn primary">Simpan QC</button></div></form>}

function MaintenancePage(){const [items,setItems]=useState<any[]>([]);const[show,setShow]=useState(false);const load=()=>api<{items:any[]}>('/api/maintenance/work-orders').then(r=>setItems(r.items));useEffect(()=>{load()},[]);async function setStatus(id:number,status:string){await api(`/api/maintenance/work-orders/${id}/status`,{method:'PATCH',body:JSON.stringify({status,resolution:status==='DONE'?'Completed from Control Center':''})});load()}return <div className="page"><PageHead title="Maintenance" desc="Preventive, corrective, dan inspection work order mesin." action={<button className="btn primary" onClick={()=>setShow(true)}><Plus size={16}/>Work Order</button>}/><div className="card-grid">{items.map(x=><div className="work-card" key={x.id}><div className="work-top"><Pill tone={x.priority==='CRITICAL'?'danger':x.priority==='HIGH'?'warn':'neutral'}>{x.priority}</Pill><span className="muted">{x.code}</span></div><h3>{x.machine}</h3><div className="muted">{x.type} · {x.scheduled_date||'tanpa jadwal'}</div><p>{x.issue||'Tidak ada issue'}</p><div className="work-foot"><Pill tone={x.status==='DONE'?'success':x.status==='IN_PROGRESS'?'blue':'neutral'}>{x.status}</Pill><select className="mini-select" value={x.status} onChange={e=>setStatus(x.id,e.target.value)}><option>OPEN</option><option>IN_PROGRESS</option><option>DONE</option></select></div></div>)}</div>{show&&<Modal title="Buat Maintenance Work Order" onClose={()=>setShow(false)}><MaintenanceForm onDone={()=>{setShow(false);load()}}/></Modal>}</div>}
function MaintenanceForm({onDone}:{onDone:()=>void}){const[f,setF]=useState<any>({code:'WO-',machine:'',type:'PREVENTIVE',priority:'MEDIUM',scheduled_date:'',technician:'',issue:''});const[err,setErr]=useState('');async function save(e:React.FormEvent){e.preventDefault();try{await api('/api/maintenance/work-orders',{method:'POST',body:JSON.stringify(f)});onDone()}catch(e:any){setErr(e.message)}}return <form className="form-grid" onSubmit={save}>{err&&<div className="alert danger full">{err}</div>}<Field label="Kode WO" value={f.code} onChange={(v:any)=>setF({...f,code:v})}/><Field label="Mesin" value={f.machine} onChange={(v:any)=>setF({...f,machine:v})}/><Field label="Type" type="select" options={['PREVENTIVE','CORRECTIVE','INSPECTION']} value={f.type} onChange={(v:any)=>setF({...f,type:v})}/><Field label="Priority" type="select" options={['LOW','MEDIUM','HIGH','CRITICAL']} value={f.priority} onChange={(v:any)=>setF({...f,priority:v})}/><Field label="Scheduled Date" type="date" value={f.scheduled_date} onChange={(v:any)=>setF({...f,scheduled_date:v})}/><Field label="Technician" value={f.technician} onChange={(v:any)=>setF({...f,technician:v})}/><div className="field full"><label>Issue<textarea value={f.issue} onChange={e=>setF({...f,issue:e.target.value})}/></label></div><div className="modal-actions full"><button type="button" className="btn ghost" onClick={onDone}>Batal</button><button className="btn primary">Simpan WO</button></div></form>}

function AuditPage(){const [items,setItems]=useState<any[]>([]);useEffect(()=>{api<{items:any[]}>('/api/audit-logs').then(r=>setItems(r.items))},[]);return <div className="page"><PageHead title="Audit Log" desc="Jejak aktivitas sensitif untuk kontrol internal dan troubleshooting."/><section className="panel table-panel"><table><thead><tr><th>Waktu</th><th>User</th><th>Action</th><th>Entity</th><th>ID</th><th>Metadata</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.created_at?.slice(0,16).replace('T',' ')}</td><td>{x.user_name||'system'}</td><td><Pill>{x.action}</Pill></td><td>{x.entity}</td><td>{x.entity_id||'—'}</td><td className="meta-cell">{x.metadata||'—'}</td></tr>)}</tbody></table></section></div>}

function UsersPage(){const [items,setItems]=useState<any[]>([]);const [show,setShow]=useState(false);const load=()=>api<{items:any[]}>('/api/users').then(r=>setItems(r.items));useEffect(load,[]);return <div className="page"><PageHead title="User & Role" desc="Kelola akun dan pembagian akses operasional." action={<button className="btn primary" onClick={()=>setShow(true)}><Plus size={16}/>User</button>}/><section className="panel table-panel"><table><thead><tr><th>User</th><th>Email</th><th>Role</th><th>Aktif</th><th>Dibuat</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><b>{x.name}</b></td><td>{x.email}</td><td><Pill>{x.role}</Pill></td><td>{x.is_active?<Pill tone="success">AKTIF</Pill>:<Pill tone="danger">OFF</Pill>}</td><td>{x.created_at?.slice(0,10)}</td></tr>)}</tbody></table></section>{show&&<Modal title="Tambah User" onClose={()=>setShow(false)}><UserForm onDone={()=>{setShow(false);load()}}/></Modal>}</div>}
function UserForm({onDone}:{onDone:()=>void}){const[f,setF]=useState<any>({name:'',email:'',password:'',role:'OPERATOR'});const[err,setErr]=useState('');async function save(e:React.FormEvent){e.preventDefault();try{await api('/api/users',{method:'POST',body:JSON.stringify(f)});onDone()}catch(e:any){setErr(e.message)}}return <form className="form-grid" onSubmit={save}>{err&&<div className="alert danger full">{err}</div>}<Field label="Nama" value={f.name} onChange={(v:any)=>setF({...f,name:v})}/><Field label="Email" value={f.email} onChange={(v:any)=>setF({...f,email:v})}/><Field label="Password" type="password" value={f.password} onChange={(v:any)=>setF({...f,password:v})}/><Field label="Role" type="select" options={['ADMIN','MANAGER','OPERATOR','QC','WAREHOUSE']} value={f.role} onChange={(v:any)=>setF({...f,role:v})}/><div className="modal-actions full"><button type="button" className="btn ghost" onClick={onDone}>Batal</button><button className="btn primary">Simpan</button></div></form>}

function PageHead({title,desc,action}:{title:string;desc:string;action?:any}){return <div className="page-head"><div><h2>{title}</h2><p>{desc}</p></div>{action}</div>}
function Field({label,value,onChange,type='text',options=[]}:{label:string;value:any;onChange:(v:any)=>void;type?:string;options?:string[]}){return <div className="field"><label>{label}{type==='select'?<select value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select>:<input type={type} value={value} onChange={e=>onChange(e.target.value)}/>}</label></div>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:any}){return <div className="modal-backdrop" onMouseDown={e=>e.currentTarget===e.target&&onClose()}><div className="modal"><div className="modal-head"><div><b>{title}</b><span>Input operasional</span></div><button className="icon-btn" onClick={onClose}><X size={18}/></button></div>{children}</div></div>}

export default function App(){const [user,setUser]=useState<User|null>(null);const[active,setActive]=useState('dashboard');const[boot,setBoot]=useState(true);useEffect(()=>{api<{user:User}>('/api/auth/me').then(r=>setUser(r.user)).catch(()=>{}).finally(()=>setBoot(false))},[]);if(boot)return <div className="loading"><RefreshCw className="spin"/> Menghubungkan ke server...</div>;if(!user)return <Login onLogin={setUser}/>;const page=active==='dashboard'?<DashboardPage/>:active==='production'?<ProductionPage/>:active==='inventory'?<InventoryPage/>:active==='purchasing'?<PurchasingPage/>:active==='quality'?<QualityPage/>:active==='maintenance'?<MaintenancePage/>:active==='audit'?<AuditPage/>:<UsersPage/>;return <Shell user={user} active={active} onNav={setActive} onLogout={async()=>{await api('/api/auth/logout',{method:'POST'});setUser(null)}}>{page}</Shell>}
